# fly.toml app configuration file generated for purple-brook-8188 on 2023-07-05T03:34:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-brook-8188"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
