# fly.toml app configuration file generated for wispy-water-3409 on 2023-07-05T03:11:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-water-3409"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
